"""
Copyright (c) 2014, Kalisko Project Leaders
Copyright (c) 2014, Google, Inc.
All rights reserved.

Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:

    * Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
    * Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer
      in the documentation and/or other materials provided with the distribution.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED
TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
"""
import os

Import('module')    # The environment for this module.
Import('src_path')  # A path to the "src" directory.

# Build all the java source files.
# TODO: Right now, this module needs to be recompiled for java changes to take effect. It
# would be nice if compiling the individual java-based modules would also trigger a
# recompile of the java sources.
module.Java(source = os.path.join(src_path, 'java'), target = os.path.join('..', '..', 'java'))

# TODO: use proper pkg-config for the jni config.
module.Append(CPPPATH = ['/usr/lib/jvm/java-7-openjdk-amd64/include'])
module.Append(LIBPATH = ['/usr/lib/jvm/java-7-openjdk-amd64/jre/lib/amd64/server'])
module.Append(LIBS = ['jvm'])

module.SharedLibrary('../kalisko_javamodule', Glob('*.c'))
