Import('module')

if not module.GetOption('clean'):
	conf = Configure(module)

	if conf.env['PLATFORM'] == 'win32':
		# List module dependencies here, use 'kalisko' for the core
		conf.env.Append(LIBS = ['kalisko'])
		
	module = conf.Finish()

module.SharedLibrary('../log_default', Glob('*.c'))