Import('module')

if not module.GetOption('clean'):
	conf = Configure(module)
	
	conf.env.Append(CPPPATH = ['../..']) # for bison

	if conf.env['PLATFORM'] == 'win32':
		# List module dependencies here, use 'kalisko' for the core
		conf.env.Append(LIBS = ['kalisko'])
		
	module = conf.Finish()

module.CFile('config_parser.c', 'config_parser.y');

module.SharedLibrary('../config', Glob('*.c'))