Import('module')

if not module.GetOption('clean'):
	conf = Configure(module)

	if conf.env['PLATFORM'] == 'win32':
		if not conf.CheckLibWithHeader('ws2_32', 'winsock2.h', 'c'):
			print('Error: Could not find ws2_32 and the corresponding winsock2.h header file!')
			Exit(1)
			
		if not conf.CheckCHeader('Ws2tcpip.h'):
			print('Error: Could not find Ws2tcpip.h header file!')
			Exit(1)
			
		# Module dependencies
		conf.env.Append(LIBS = ['kalisko'])
			
	module = conf.Finish()

module.SharedLibrary('../socket', Glob('*.c'))