"""
Copyright (c) 2008, Kalisko Project Leaders
All rights reserved.

Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:

    * Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
    * Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer
      in the documentation and/or other materials provided with the distribution.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED
TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
"""
Import('module')

if not module.GetOption('clean'):
	conf = Configure(module)
	
	if not conf.CheckLibWithHeader('m', 'math.h', 'C'):
		print('Error: Could not find the m library and/or the math.h header file!')
		Exit(1)
		
	if module['PLATFORM'] != 'win32':
		if not conf.CheckLibWithHeader('GLU', 'GL/glu.h', 'C'):
			print('Error: Could not find the GLU library and/or the GL/glu.h header file!')
			Exit(1)		
			
		if not conf.CheckLibWithHeader('GLEW', 'GL/glew.h', 'C'):
			print('Error: Could not find the GLEW library and/or the GL/glew.h header file!')
			Exit(1)	
	else:
		module.ParseConfig('pkg-config --libs --cflags glew')
			
		if not conf.CheckLib('opengl32'):
			print('Error: Could not find the opengl32 library!')
			Exit(1)
			
		if not conf.CheckLib('glu32'):
			print('Error: Could not find the glu32 library!')
			Exit(1)
				
	module = conf.Finish()

module.SharedLibrary('../kalisko_scene', Glob('*.c'))
