"""
Copyright (c) 2008, Kalisko Project Leaders
All rights reserved.

Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:

    * Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
    * Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer
      in the documentation and/or other materials provided with the distribution.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED
TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
"""
import os
Import('module')
Import('custom_tests')

conf = Configure(module, custom_tests)
check = True
	
if module['PLATFORM'] == 'win32':
	thirdPartyDir = os.path.join(module.GetLaunchDir(), '3rd_party')
	check = check and os.path.exists(thirdPartyDir)
else:
	cmd = os.popen('js-config --version')
	version = cmd.read()
	
	if len(version) > 1:
		try:
			conf.env.ParseConfig('js-config --libs --cflags')
		except:
			check = False
	else:
		check = False

module = conf.Finish()

if check:
	if module['PLATFORM'] == 'win32':
		module.Append(LIBPATH = [thirdPartyDir + '/lib'])
		module.Append(CPPPATH = [thirdPartyDir + '/include'])
		module.Append(LIBS=['mozjs'])
		module.Command("../../mozjs.dll", File(thirdPartyDir + '/bin/mozjs.dll').srcnode(), Copy("$TARGET", "$SOURCE"))
		module.Command("../../libgcc_s_sjlj-1.dll", File(thirdPartyDir + '/bin/libgcc_s_sjlj-1.dll').srcnode(), Copy("$TARGET", "$SOURCE"))

	module.SharedLibrary('../kalisko_lang_javascript', Glob('*.c'))
else:
	print('A required library for the \'lang_javascript\' module is not available, skipping build...')
